images:
  # - path: "xxx.jpg"  # Image path
  #   duration: 4.0             # Display duration (in seconds)
  #   # Translation: [x, y] percentage. Positive x is right, positive y is down.
  #   # This means the view pans 5% to the right and 2% up over 1 second.
  #   translation: [5, -2]
  #   # Scale: The final zoom factor. 1.0 is no zoom.
  #   # This means the view zooms from 1x to 1.2x over 1 second.
  #   scale: 1.2
  - path: "examples/single/ref_image.png"
    duration: 2  # seconds
    translation: [0, 0] # [dx, dy] - pixels per second (approximately)
    scale: 1.0      # Scale factor (1.0 = no change, >1.0 zoom in, <1.0 zoom out)
  - path: "examples/single/ref_image.png"
    duration: 3.0
    translation: [-7, -7]
    scale: 1.0